general:
  machine_pickle_file: data.pickle

logging:
  level: INFO # level at which logging should start
  format:
    time: "%Y-%m-%d %H:%M.%S" # other example: "iso"
    renderer: console # or: json

ceph:
  config: ./.ceph/ceph.conf
  keyring: ./.ceph/ceph.client.admin.keyring
  systemd_file_name_templates:
    mds: "ceph-{fsid}@mds.{host}.service"
    mgr: "ceph-{fsid}@mgr.{host}.service"
    mon: "ceph-{fsid}@mon.{host}.service"
    osd: "ceph-{fsid}@osd.{osd_id}.service"
    rgw: "ceph-{fsid}@rgw.{host}.service"

# fill in correct path to private key
ssh:
  private_key: /home/USER/.ssh/cloud.private
  hosts:
    testbed-node-0:
      address: 192.168.16.10
      user: dragon
    testbed-node-1:
      address: 192.168.16.11
      user: dragon
    testbed-node-2:
      address: 192.168.16.12
      user: dragon

kubernetes:
  config: ./k8s/config

rook:
  cluster:
    name: osism-ceph
    namespace: rook-ceph
  ceph:
    image: quay.io/ceph/ceph:v18.2.1
  flags:
    mds_support_metadata_name: False

migration_modules:
- example
- create_rook_cluster
- migrate_osds
- migrate_osd_pools
- migrate_mds
- migrate_mds_pools
- migrate_mgrs
- migrate_rgws
- migrate_rgw_pools
