[build-system]
requires = [ "setuptools", "wheel" ]
build-backend = "setuptools.build_meta"

[project]
name = "Rookify"
version = "0.0.1"
requires-python = ">=3.9"
readme = "README.md"
description = "Migration tool"
license.file = "LICENSE"
