general:
  machine_pickle_file: str(required=False)

logging:
  level: str()
  format:
    time: str()
    renderer: str()

ceph:
  config: str()
  flags: map(key=str(), required=False) # @TODO: Replace with include once we support at least one Ceph flag
  keyring: str()
  systemd_file_name_templates: include("systemd_file_name_templates", required=False)

ssh:
  private_key: str()
  hosts: map(include("ssh_host"), key=str(), min=1)

kubernetes:
  config: str()
  flags: map(key=str(), required=False) # @TODO: Replace with include once we support at least one Kubernetes flag

rook:
  cluster:
    name: str()
    namespace: str()
    max_mgr_count: int(required=False)
    max_mon_count: int(required=False)
    mds_placement_label: str(required=False)
    mgr_placement_label: str(required=False)
    mon_placement_label: str(required=False)
    osd_placement_label: str(required=False)
    rgw_placement_label: str(required=False)
  ceph:
    image: str()
    public_network: regex("^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(/(3[0-2]|2[0-9]|1[0-9]|[0-9]))?$", required=False)
    cluster_network: regex("^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(/(3[0-2]|2[0-9]|1[0-9]|[0-9]))?$", required=False)
  flags: include("rook_flags", required=False)

migration_modules: list(str())
---
rook_flags:
    mds_support_metadata_name: bool()
---
ssh_host:
    address: ip()
    user: str()
---
systemd_file_name_templates:
    mds: str(required=False)
    mgr: str(required=False)
    mon: str(required=False)
    osd: str(required=False)
    rgw: str(required=False)
