general:
  machine_pickle_file: str(required=False)

logging:
  level: str()
  format:
    time: str()
    renderer: str()

ceph:
  config: str()
  keyring: str()

ssh:
  private_key: str()
  hosts: map(include("ssh_host"), key=str(), min=1)

kubernetes:
  config: str()

rook:
  cluster:
    name: str()
    namespace: str()
    max_mgr_count: int(required=False)
    max_mon_count: int(required=False)
    mds_placement_label: str(required=False)
    mgr_placement_label: str(required=False)
    mon_placement_label: str(required=False)
    osd_placement_label: str(required=False)
    rgw_placement_label: str(required=False)
  ceph:
    image: str()
    public_network: regex("^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(/(3[0-2]|2[0-9]|1[0-9]|[0-9]))?$", required=False)
    cluster_network: regex("^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(/(3[0-2]|2[0-9]|1[0-9]|[0-9]))?$", required=False)

migration_modules: list(str())
---
ssh_host:
    address: ip()
    user: str()
